# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3e1dfd810055dfd2b3be691bd303bc888b6a818f80877cc80b6558d75ec15772a2cbf57fe39e2dd3abcf1bcc7ae391a11eb1118264bc4963c570d077a18010b7

test:
  secret_key_base: 3c2c80b0e9776d28fc6719eaa41fe696e8c1c1466e02e5ce9a5ad553211aab471644decd5e8893e617724363ad43d3a1abf3576cf441941ab77e29bfc1bf037e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
